version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/HeroHeader/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
